# Generated by Django 3.1.1 on 2021-04-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_view', '0006_auto_20210424_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactagent',
            name='email',
            field=models.EmailField(default='mail@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactagent',
            name='property_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='public_view.property'),
            preserve_default=False,
        ),
    ]
